name: Pipeline Diario de Cotacoes

on:
  schedule:
  
    - cron: '14 11 * * *'
  

  workflow_dispatch: 


jobs:
  executar-etl:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1. Pegar os arquivos do repositorio
        uses: actions/checkout@v4

      - name: 2. Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 3. Instalar as bibliotecas necessarias
        run: pip install -r requirements.txt

      - name: 4. Rodar o Pipeline
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: 5. Salvar o banco de dados de volta no GitHub
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          git add meu_banco.db
          git commit -m "🤖 [Bot] Atualiza banco de dados com as cotações do dia" || echo "Nenhuma nova cotação para salvar hoje"
          git push